<?php

class RootEntity {

    /**
     * @type:hidden
     * @uiignore:true
    */
	public $id;
    /**
     * @uiignore:true
     */
    public $_error;
    /**
     * @uiignore:true
     */
	public $_dialog;
    /**
     * @uiignore:true
     */
	public $_activetab;
    /**
     * @uiignore:true
     */
	public $updated_date;
    /**
     * @type:hidden
     * @uiignore:true
     */
	public $version;
}
?>