<?php
$Registry = array (
	'Templates' => array (
		'default' => 'AdminSubscriptionView.default.html',
		'viewmail' => 'AdminSubscriptionView.viewmail.html',
		'viewsubscribers' => 'AdminSubscriptionView.viewsubscribers.html',
		'empty' => 'AdminSubscriptionView.empty.html',
		'emptymail' => 'AdminSubscriptionView.empty.html',
		'emptysubscribers' => 'AdminSubscriptionView.empty.html',
		'emptycategory' => 'AdminSubscriptionView.empty.html',
		'actioncategory' => 'AdminSubscriptionView.actioncategory.html',
		'actionmail' => 'AdminSubscriptionView.actionmail.html',
		'actionsubscriber' => 'AdminSubscriptionView.actionsubscriber.html',
		'finish_save' => 'finish.html',
		'finish_delete' => 'finish.html',
		'finish' => 'finish.html',
		'message' => 'message.html',
	),
);
?>