<?php
$Registry = array (
	'Templates' => array (
		'default' => 'AdminDocumentView.default.html',
		'action' => 'AdminDocumentView.action.html',
		'details' => 'AdminDocumentView.details.html',
		'empty' => 'AdminDocumentView.empty.html',
		'finish_save' => 'finish.html',
		'finish_delete' => 'finish.html',
		'finish' => 'finish.html',
		'message' => 'message.html',
		'auth' => 'auth.html',
	),
);
?>