<?php
$Registry = array (
	'Templates' => array (
		'default' => 'AdminView.default.html',
		'auth' => 'AdminView.auth.html',
		'message' => 'AdminView.message.html',
		'clear' => 'AdminView.clear.html',
	),
	'Properties' => array(
		'Tasks' => array(
			'0' => 'WebSiteControl',
			'1' => 'AdminPages',
			'2' => 'AdminStatistic',
			'3' => 'AdminMenuItems',
			'4' => 'AdminSubscription',
			'5' => 'AdminNews',
			'6' => 'AdminHeader',
			'9' => 'AdminModule',			
			'10' => 'AdminDocument',
			'11' => 'AdminQuotation',
			'100' => 'Logoff',
		),
		'Clear' => array(
			'1' => 'NewsList',
		),
	),
);
?>