<?php
$Registry = array (
	'Templates' => array (
		'default' => 'AdminMemberView.default.html',
		'viewmember' => 'AdminMemberView.viewmember.html',
		'register' => 'AdminMemberView.form.html',
		'end' => 'AdminMemberView.end.html',

		'empty' => 'AdminMemberView.empty.html',
		'action' => 'AdminMemberView.action.html',
		'finish_save' => 'finish.html',
		'finish_delete' => 'finish.html',
		'finish' => 'finish.html',
		'message' => 'message.html',
	),
);
?>