<?php
$Registry = array (
	'Properties' => array (
		'Tasks' => array (
			'6' => array (
				'view' => array (
					'handlerMethod' => 'selectNews',
					'scheme' => 'default',
				),
				'getnews' => array (
					'handlerMethod' => 'getNews',
					'scheme' => 'default',
				),
				'settings' => array (
					'minPerm' => 2,
					'handlerMethod' => 'getSettings',
					'scheme' => 'default',
				),
			),
		),
	),
);
?>