<?php
$Registry = array (
	'Properties' => array (
		'Sections' => array (
			'1' => array(/* HomePage*/
        'a' => '',
        'h' => '',
        'm' => '1',
        'url' => '',
      ),
			'2' => array(/* Registration */
			  'a' => 'Security',
        'h' => 'Security',
        'm' => '2',
        'url' => 'Registration', 			
			),
			'3' => array( /* Admin */
				'a' => 'Admin',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'5' => array( /*  Things  */
				'a' => 'Things',
				'h' => 'Things',
				'm' => '5',
				'url' => 'Things',
			),
			'6' => array( /*  Things  */
				'a' => 'Header',
				'h' => 'Admin',
				'm' => '5',
				'url' => 'Header',
			),
			'7' => array( /*  Counter  */
				'a' => 'Counter',
				'h' => 'Counter',
				'm' => '5',
				'url' => 'Counter',
			),
			'8' => array( /*  MetaInfo  */
				'a' => 'MetaInfo',
				'h' => 'Menu',
				'm' => '6',
				'url' => 'MetaInfo',
			),
			
			//Admin and service structures
			'10' => array( /*Menu Panel edit */
				'a' => 'Menu',
				'h' => 'Menu',
				'm' => '6',
				'url' => 'Things',
			),
			'11' => array( /* Admin Header edit */
				'a' => 'AdminHeader',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'12' => array( /* News */
				'a' => 'News',
				'h' => 'News',
				'm' => '8',
				'url' => 'News',
			),
			'13' => array( /* Quotation */
				'a' => 'Quotation',
				'h' => 'Quotation',
				'm' => '9',
				'url' => 'Quotation',
			),			
			'14' => array( /* Admin Main Message edit */
				'a' => 'AdminMessage',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'15' => array( /* Admin Pages edit */
				'a' => 'AdminPages',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'16' => array( /* Admin News edit */
				'a' => 'AdminNews',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'17' => array( /* Admin Menu Items */
				'a' => 'AdminMenuItems',
				'h' => 'Menu',
				'm' => '3',
				'url' => 'Admin',
			),
			'18' => array( /* Admin Subscription edit */
				'a' => 'AdminSubscription',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'19' => array( /* Admin Quotation edit */
				'a' => 'AdminQuotation',
				'h' => 'Quotation',
				'm' => '3',
				'url' => 'Admin',
			),
            '20' => array( /* Admin Content Item*/
                'a' => 'AdminContentItem',
                'h' => 'Lang',
                'm' => '3',
                'url' => 'Admin',
            ),

			'21' => array( /* Admin Members edit */
				'a' => 'AdminMember',
				'h' => 'Admin',
				'm' => '3',
				'url' => 'Admin',
			),
			'24' => array( /* Admin Listing edit */
				'a' => 'AdminModule',
				'h' => 'AdminModule',
				'm' => '3',
				'url' => 'Admin',
			),
			'28' => array( /* Admin Statistic Message edit */
				'a' => 'AdminStatistic',
				'h' => 'Statistic',
				'm' => '3',
				'url' => 'Admin',
			),
			'29' => array( /* Admin Document edit */
				'a' => 'AdminDocument',
				'h' => 'Document',
				'm' => '3',
				'url' => 'Admin',
			),
			'30' => array( /* Document edit */
				'a' => 'Docs',
				'h' => 'Document',
				'm' => '7',
				'url' => 'Docs',
			),
            '100' => array( /* COMMON */
                'a' => 'CommonUtils',
                'h' => 'CommonUtils',
                'm' => '3',
                'url' => 'Admin',
            ),
            '101' => array( /* Quotation */
                'a' => 'Quotation',
                'h' => 'Quotation',
                'm' => '101',
                'url' => 'Quotation',
            ),
            '103' => array( /* COMMON */
                'a' => 'GlobalSystemSettings',
                'h' => 'GlobalSystemSettings',
                'm' => '103',
                'url' => 'Admin',
            ),
            '104' => array( /* COMMON */
                'a' => 'Log',
                'h' => 'Log',
                'm' => '104',
                'url' => 'Admin',
            ),
			'200' => array( /* Search edit */
				'a' => 'Search',
				'h' => 'Search',
				'm' => '5',
				'url' => 'search',
			),

		),
		'Guides' => array(
            'language' => array(
                'table' => 'language',
            ),
            'country' => array(
				'table' => 'country',
			),
            'module' => array(
                'table' => 'module',
            ),
            'contenttype' => array(
                'table' => 'contenttype',
            ),
            'month' => array(
				'table' => 'month',
			),		
			'gender' => array(
				'table' => 'gender',
			),		
		),
	),
);
?>